#include "task.cpp"
// allTasks is generated by user
std::queue<ITask*> allTasks;
bool client = true;
time_t rawtime;
struct tm * timeinfo;

char buffer[80];
std::ofstream fTime;
void FindSolution() {
	MPI_Status st;
	std::stringstream ss;
	ss << rank;
	std::string nameFile = "Loading" + ss.str();
	nameFile += ".txt";
	std::ofstream fLoading(nameFile);
	if (client) {
		MPI_Recv(&iteration, 1, MPI_INT, 0, 10005, lib.currentComm, &st);
		client = false;
	}
	for (iteration = 0; iteration < maxiter && CheckConditions(); iteration++) {
		/* if (rank_old == 0)*/ printf("%d::  --------------------START ITERATION %d---------------------\n", rank, iteration);
		for (auto &i : newResult) i = 0;
		for (auto &i : oldResult) i = 0;

		while (!allTasks.empty()) {
			Task *t = dynamic_cast<Task*>(allTasks.front());
			if (iteration != 0) t->ReceiveFromNeighbors(lib.currentComm);
			lib.queueRecv.push(t);
			allTasks.pop();
		}

		while (!queueRecv.empty()) {
			Task *t = dynamic_cast<Task*>(lib.queueRecv.front());
			if (iteration != 0) t->WaitBorders();
			pthread_mutex_lock(&lib.mutex_get_task);
			lib.currentTasks.push(t);
			pthread_mutex_unlock(&lib.mutex_get_task);
			lib.queueRecv.pop();
		}
		fprintf(stderr, "%d:: count of tasks = %d\n", lib.rank, lib.currentTasks.size());

		lib.StartWork();
				
		GenerateResultOfIteration(lib.reduceComm);

		while (!queueRecv.empty()) {
			Task *t = dynamic_cast<Task*>(lib.queueRecv.front());
			t->SendToNeighbors(lib.currentComm);
			allTasks.push(t);
			lib.queueRecv.pop();
		}
		fLoading << "iteration " << iteration << "::  " << allTasks.size() << "\ttasks\n";
		if (lib.rank_old == 0) printf("%d:: --------------------FINISH ITERATION %d---------------------\n", lib.rank, iteration);
	}
	lib.CloseLibraryComponents();
	
	fLoading.close();
}

int main(int argc, char **argv) {
	time(&rawtime);
	timeinfo = localtime(&rawtime);
	if (rank == 0) {		
		strftime(buffer, 80, "%H:%M:%S", timeinfo);
		puts(buffer);
		std::stringstream ss;
		ss << lib.numberOfConnection;
		std::string nameFile = "time_client" + ss.str();
		nameFile += ".txt";
		fTime.open(nameFile);
		fTime << "client's processes start in " << buffer << "\n";
		fTime.close();
	}
	lib.LibraryInitialize(argc, argv, true);
	// If work exist
	if (map.size())	{
		GenerateBasicConcepts();
		FindSolution();
		GenerateResult(lib.currentComm);
	}
	MPI_Finalize();
	return 0;
}
