#include "task.h"
// allTasks is generated by user
std::queue<ITask*> allTasks;
std::ofstream fTime;
std::vector<int> map;
time_t rawtime;
struct tm * timeinfo;

char buffer[80];

double residual = 1;
double eps = 1e-8;
Library lib;

bool CheckConditions() {
	if (residual > eps) return true;
	else return false;
}
void FindSolution() {	
	MPI_Status st;
	
	std::stringstream ss;
	ss << lib.rank;
	std::string nameFile = "Loading" + ss.str();
	nameFile += ".txt";
	std::ofstream fLoading(nameFile);

	for (iteration = 0; iteration < maxiter && CheckConditions(); iteration++) {
		if (lib.rank == 0) printf("%d::  --------------------START ITERATION %d---------------------\n", lib.rank, iteration);
		for (auto &i : newResult) i = 0;
		for (auto &i : oldResult) i = 0;
		auto t_start = std::chrono::high_resolution_clock::now();
		while (!allTasks.empty()) {
			Task *t = dynamic_cast<Task*>(allTasks.front());
			if (iteration != 0) t->ReceiveFromNeighbors(lib.currentComm);
			lib.queueRecv.push(t);
			allTasks.pop();
		}

		while (!lib.queueRecv.empty()) {
			Task *t = dynamic_cast<Task*>(lib.queueRecv.front());
			if (iteration != 0) t->WaitBorders();
			pthread_mutex_lock(&lib.mutex_get_task);
			lib.currentTasks.push(t);
			pthread_mutex_unlock(&lib.mutex_get_task);
			lib.queueRecv.pop();
		}

		fprintf(stderr, "%d:: count of tasks = %d\n", lib.rank, lib.currentTasks.size());
		
		lib.StartWork();

		if (lib.changeExist) {
			lib.changeExist = false;
			if (lib.rank == 0)
				for (int k = lib.size_old; k < lib.size; k++)
					MPI_Send(&iteration, 1, MPI_INT, k, 10005, lib.currentComm);
		}
		fprintf(stderr, "%d::get to generate result of iteration\n", lib.rank);
		GenerateResultOfIteration(lib.reduceComm);

		while (!lib.queueRecv.empty()) {
			Task *t = dynamic_cast<Task*>(lib.queueRecv.front());
			t->SendToNeighbors(lib.currentComm);
			lib.queueRecv.pop();
			allTasks.push(t);
		}
		auto t_end = std::chrono::high_resolution_clock::now();
		if (lib.rank == 0) {
			printf("%d:: res = %e\n", lib.rank, residual);
			printf("%d:: --------------------FINISH ITERATION %d---------------------\n", lib.rank, iteration);

		}
		if (lib.rank == 0) {
			fTime << "iteration " << iteration << "::  " << std::chrono::duration<double, std::milli>(t_end - t_start).count() << " ms\n";
		}
		fLoading << "iteration " << iteration << "::  " << allTasks.size() << "\ttasks\n";
	}	
	lib.CloseLibraryComponents();
	fLoading.close();
}

int main(int argc, char **argv) {
	fTime.open("time_server.txt");
	time(&rawtime);
	timeinfo = localtime(&rawtime);
	strftime(buffer, 80, "%H:%M:%S", timeinfo);
	puts(buffer);
	lib.LibraryInitialize(argc, argv, false);
	if (lib.rank == 0) 	fTime << "servers's processes start in " << buffer << "\n";
	GenerateBasicConcepts();
	GenerateQueueOfTask(allTasks, map);
	std::vector<int> tmp(map.size());
	lib.map.resize(map.size());
	MPI_Allreduce(map.data(), lib.map.data(), map.size(), MPI_INT, MPI_SUM, lib.currentComm);
	FindSolution();
	GenerateResult(lib.currentComm);
	MPI_Finalize();
	fTime.close();
	return 0;
}
